### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by probonopd** [stuha/translator#1]
```
sudo apt install git
git clone https://github.com/stuha/translator.git
cd translator && sudo python setup.py install
sudo apt install python-setuptools python-requests python-parse

me@host:~/translator$ translator you are so beautiful!
Traceback (most recent call last):
  File "/usr/local/bin/translator", line 11, in <module>
    load_entry_point('translator==0.0.1', 'console_scripts', 'translator')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/translator/translator.py", line 18, in <module>
ImportError: No module named parse

me@host:~/translator$ cat /etc/lsb-release 
DISTRIB_ID=neon
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="KDE neon Developer Edition"
```

**Comment by wang-borong** [comment]
Sorry，This tool is based on Python3. You can run `sudo python3 setup.py install` to install it.
Thanks!
